framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: ertanexchange
                        type: direct
                        default_publish_routing_key: [ ertan1, ertan2, ertan3, ertan4 ]
                    queues:
                        ertan_1:
                            binding_keys: [ertan1]
                        ertan_2:
                            binding_keys: [ertan2]
                        ertan_3:
                            binding_keys: [ertan3]
                        ertan_4:
                            binding_keys: [ertan4]

            ertan_async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queues:
                        ertan_async: ~

            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            'App\Message\MessageInterface': async
            'App\Message\ErtanNotification': ertan_async
