framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            transport1:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: ertanlar
                        type: direct
                    queues:
                        ertan_1:
                            binding_keys: [ ertan_1 ]
                        ertan_2:
                            binding_keys: [ ertan_2 ]
                        ertan_3:
                            binding_keys: [ ertan_3 ]
                        ertan_4:
                            binding_keys: [ ertan_4 ]


            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            'App\Message\MessageInterface': transport1



